name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  Dockerhub:
    name: Publish image to Dockerhub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS Dependencies
        run: yarn
      - name: Compile TypeScript
        uses: icrawl/action-tsc@v1
        with:
          build: src
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: favware/graphql-pokemon
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  GCloud:
    name: Publish image to Google Cloud Platform
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup GCloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS Dependencies
        run: yarn
      - name: Compile TypeScript
        uses: icrawl/action-tsc@v1
        with:
          build: src
      - name: Configure gcloud
        run: gcloud auth configure-docker
      - name: Build Docker image
        run: docker build . --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/graphql-pokemon
      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/graphql-pokemon
      - name: Deploy latest image to Google Cloud Run
        run: gcloud run deploy graphql-pokemon --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/graphql-pokemon --region=europe-west1 --project=${{ secrets.GCLOUD_PROJECT }} --platform=managed --allow-unauthenticated
