name: Update Showdown Formats

on:
  push:
    branches:
      - master

# on:
#   schedule:
#     - cron: '0 2 * * *'

jobs:
  UpdateFormats:
    name: Update Showdown Formats
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Restore CI Cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
    - name: Install Deps
      run: yarn
    - name: Run Updater
      run: yarn scripts:formatsupdater
    - name: Install Hub
      run: sudo snap install hub --classic
    - name: Commit any changes
      run: |
        GITHUB_REPO_URL="https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git";
        git config --local user.email "${GITHUB_EMAIL}";
        git config --local user.name "${GITHUB_USER}";
        git checkout -b favware-bot/update-smogon-formats/`date +%F-%H-%M`;
        git commit -sam "feat: update smogon formats";
        hub pull-request -p -m "*bleep bloop* I updated the Smogon tier list" -l "SEM: N/A,Meta: Smogon Tier Update" -a "favna" -r "favna"
      env:
        GITHUB_USER: ${GITHUB_ACTOR}
        GITHUB_EMAIL: favwarebot@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}